language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.3

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-android-m2repository

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

env:
  matrix:
    # uncomment the following lines to test the various emulators for speed
    #- API=android-15 ABI=armeabi-v7a
    - API=android-16 ABI=armeabi-v7a
    #- API=android-17 ABI=armeabi-v7a
    #- API=android-18 ABI=armeabi-v7a
    #- API=android-19 ABI=armeabi-v7a
    #- API=android-21 ABI=armeabi-v7a
    #- API=android-22 ABI=armeabi-v7a
    #- API=android-24 ABI=armeabi-v7a
    #- API=android-24 ABI=arm64-v8a

before_install:
 - chmod +x gradlew

# Emulator Management: Create, Start and Wait
before_script:
  # uncomment the following lines once there are instrumentation tests
  #- echo no | android create avd --force --name test --target $API --abi $ABI
  #- emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./gradlew clean assembleDebug codeChecks -PdisablePreDex
  # uncomment the following lines once there are instrumentation tests
  #- android-wait-for-emulator
  #- android list target
  #- adb shell input keyevent 82 &
  #- ./gradlew connectedDebugAndroidTest -PdisablePreDex --continue --stacktrace

after_success:
  #- bash <(curl -s https://codecov.io/bash)